name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build APK using complete Buildozer image
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/app \
            ghcr.io/coding-cat/buildozer-android:latest \
            bash -c "cd /home/user/app && buildozer android debug"