name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker pull the4thdoctor/buildozer:latest

      - name: Build APK with Buildozer
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/app \
            the4thdoctor/buildozer:latest \
            bash -c "cd /home/user/app && buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Btapp-debug.apk
          path: bin/*.apk