name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with prebuilt Buildozer image
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/app \
  debackerdev/buildozer-android bash -c "cd /home/user/app && buildozer android debug"